# Generated by Django 5.0.2 on 2024-05-30 17:41

import autoslug.fields
import django.db.models.deletion
import food_shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=255,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Слаг категории",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="categories",
                        verbose_name="Фото категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="ProductCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания продуктовой корзины",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь продуктовой корзины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продуктовая корзина",
                "verbose_name_plural": "Продуктовые корзины",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Cлаг подкатегории",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="subcategories",
                        verbose_name="Фото подкатегории",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="food_shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "Подкатегории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Название продукта"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Cлаг продукта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость продукта",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        choices=[
                            ("kg", "Килограммы"),
                            ("lt", "Литры"),
                            ("pcs", "Штуки"),
                        ],
                        default="kg",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "icon_small",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products_small/",
                        verbose_name="Фото продукта маленькое",
                    ),
                ),
                (
                    "icon_middle",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products_middle/",
                        verbose_name="Фото продукта среднее",
                    ),
                ),
                (
                    "icon_big",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products_big/",
                        verbose_name="Фото продукта большое",
                    ),
                ),
                (
                    "date_add",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления продукта"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="food_shop.subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-date_add"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество продуктов в корзине"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания корзины покупок пользователя",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="food_shop.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "product_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart_products",
                        to="food_shop.productcart",
                        verbose_name="Продуктовая корзина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт в корзине у пользователя",
                "verbose_name_plural": "Продукты в корзинах у пользователей",
                "ordering": ["-date_created"],
                "unique_together": {("product_cart", "product")},
            },
        ),
    ]
