# Generated by Django 5.0.2 on 2024-05-26 20:27

import autoslug.fields
import django.db.models.deletion
import food_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=255,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Слаг категории",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=250,
                        verbose_name="Описание категории",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="food_shop/images/categories",
                        verbose_name="Фото категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Cлаг подкатегории",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="food_shop/images/subcategories",
                        verbose_name="Изображение",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="food_shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "Подкатегории",
                "ordering": ("name",),
            },
        ),
    ]
