# Generated by Django 5.0.2 on 2024-05-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shoppingcartproduct",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="shoppingcartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart_products",
                to="food_shop.product",
                verbose_name="Продукт",
            ),
        ),
    ]
