# Generated by Django 5.0.2 on 2024-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="level",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="tree_id",
        ),
    ]
