# Generated by Django 5.0.2 on 2024-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartproduct",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Количество продуктов в корзине"
            ),
        ),
    ]
