# Generated by Django 5.0.2 on 2024-05-27 10:07

import autoslug.fields
import django.db.models.deletion
import food_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0002_remove_subcategory_level_remove_subcategory_lft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="media/categories",
                verbose_name="Фото категории",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="icon",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="media/subcategories",
                verbose_name="Фото подкатегории",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Название продукта"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        populate_from=food_shop.models.get_slug,
                        unique=True,
                        verbose_name="Cлаг продукта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость продукта",
                    ),
                ),
                (
                    "icon_small",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/products_small/",
                        verbose_name="Фото продукта маленькое",
                    ),
                ),
                (
                    "icon_middle",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/products_middle/",
                        verbose_name="Фото продукта среднее",
                    ),
                ),
                (
                    "icon_big",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/products_big/",
                        verbose_name="Фото продукта большое",
                    ),
                ),
                (
                    "date_add",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата добавления продукта"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="food_shop.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="food_shop.subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("date_add",),
            },
        ),
    ]
