# Generated by Django 5.0.2 on 2024-06-02 11:42

import autoslug.fields
import core.constants
import django.core.validators
import food_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0002_alter_shoppingcartproduct_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ("name",),
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                verbose_name="Название категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                populate_from=food_shop.models.get_slug,
                unique=True,
                verbose_name="Слаг категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                unique=True,
                verbose_name="Название продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Минимальное стоимость продукта должна быть не меньше 1.",
                    ),
                    django.core.validators.MaxValueValidator(
                        1000,
                        message="Максимальная стоимость продукта должна быть не больше 1000.",
                    ),
                ],
                verbose_name="Стоимость продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                populate_from=food_shop.models.get_slug,
                unique=True,
                verbose_name="Cлаг продукта",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartproduct",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Минимальное количество продукта должно быть не меньше 1.",
                    ),
                    django.core.validators.MaxValueValidator(
                        1000,
                        message="Максимально количество продукта не превышает 1000.",
                    ),
                ],
                verbose_name="Количество продуктов в корзине",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=core.constants.LenghtField["MAX_LENGHT_USERNAME"],
                populate_from=food_shop.models.get_slug,
                unique=True,
                verbose_name="Cлаг подкатегории",
            ),
        ),
    ]
