# Generated by Django 5.0.2 on 2024-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0003_remove_category_description_alter_category_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_add",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления продукта"
            ),
        ),
    ]
