# Generated by Django 5.0.2 on 2024-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0004_alter_product_date_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="icon_big",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products_big/",
                verbose_name="Фото продукта большое",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="icon_middle",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products_middle/",
                verbose_name="Фото продукта среднее",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="icon_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products_small/",
                verbose_name="Фото продукта маленькое",
            ),
        ),
    ]
