# Generated by Django 5.0.2 on 2024-06-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_in_cart",
                to="food_shop.product",
                verbose_name="Продукт",
            ),
        ),
    ]
