# Generated by Django 5.0.2 on 2024-05-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_shop", "0008_alter_productcart_options_alter_productcart_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="food_shop.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "product_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart_products",
                        to="food_shop.productcart",
                        verbose_name="Продуктовая корзина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт в корзине у пользователя",
                "verbose_name_plural": "Продукты в корзинах у пользователей",
                "unique_together": {("product_cart", "product")},
            },
        ),
    ]
